version: "3.9"

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: phonebook
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    volumes:
      - phonebook-postgres:/var/lib/postgresql/data

  phonebook:
    build:
      context: .
    volumes:
      - ./phonebook:/opt/app
    links:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  phonebook-postgres:
